"""
train_bow_crnn.py
=================
Trains a CTC CRNN model for whole bow-number OCR and exports ONNX. The default
37-class model reads 1-3 digits with an optional A-Z prefix (for example "5",
"E43", or "Z128"). ``--vocabulary numeric`` produces an 11-class digit-only
model and strips a leading letter from real training and validation labels.

KEY DESIGN PRINCIPLE — Pipeline-matched synthetic data
-------------------------------------------------------
The synthetic training images are generated by rendering bow labels and
then applying the same preprocessing pipeline as BowNumberReader:

    render gray card → upscale → CLAHE → mild sharpen → polarity normalize

This produces contrast-normalized grayscale images that retain thin characters on
gray cards and match the real crops fed to the CRNN at inference time.

Inference contract (must match BowNumberReader)
-------------------------------------------------
    Input  "input"  : float32  (1, 1, H=48, W=60)    normalised [0,1]
    Output "output" : float32  (T, 1, NUM_CLS)        time-major logits
    Decode          : greedy CTC — argmax per timestep, collapse consecutive
                       repeats, drop blank (index 0)

This is a genuine sequence model: a single forward pass over the whole card
crop reads the complete label. There's no per-character
cropping, classification, or heuristic stitching involved -- CTC decoding is
what turns per-timestep logits into a string, from ONE pass over ONE image.

Usage
-----
    # Synthetic only (good baseline, ~5 min on CPU)
    python scripts/train_bow_crnn.py --epochs 30 --samples 5000 --output bow_crnn.onnx

    # Add real labelled crops for best accuracy
    # Convention: crops/<label>_<anything>.png  e.g. crops/E43_frame042.png
    python scripts/train_bow_crnn.py --epochs 50 --real-data crops/ --output bow_crnn.onnx

    # Verify an existing model
    python scripts/train_bow_crnn.py --verify bow_crnn.onnx

Requirements
------------
    pip install torch onnx onnxscript opencv-python numpy pillow
"""

import argparse
import os
import random
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
from PIL import Image, ImageDraw, ImageFont
from torch.utils.data import Dataset, DataLoader

from bow_ocr_labels import (
    ALPHA_PREFIXES,
    BLANK_INDEX,
    CHARACTERS,
    DIGITS,
    NUM_CLASSES,
    is_valid_bow_label,
    normalize_bow_label,
)
from ocr_preprocessing import normalize_grayscale_card


# ─── Charset ─────────────────────────────────────────────────────────────────

# Model class 0 is the CTC blank. Recognizable characters start at class 1.
BLANK_IDX = BLANK_INDEX
CHAR_TO_IDX = {character: index + 1 for index, character in enumerate(CHARACTERS)}
NUMERIC_ONLY = False


def configure_vocabulary(name: str) -> None:
    """Configure label encoding and output width for one training invocation."""
    global CHARACTERS, NUM_CLASSES, CHAR_TO_IDX, NUMERIC_ONLY
    if name not in {"alphanumeric", "numeric"}:
        raise ValueError(f"Unsupported OCR vocabulary: {name}")
    NUMERIC_ONLY = name == "numeric"
    CHARACTERS = DIGITS if NUMERIC_ONLY else DIGITS + ALPHA_PREFIXES
    NUM_CLASSES = len(CHARACTERS) + 1
    CHAR_TO_IDX = {
        character: index + 1 for index, character in enumerate(CHARACTERS)
    }


def training_label(value: str) -> str:
    """Normalize a crop label for the configured model vocabulary."""
    return normalize_bow_label(value, ignore_alpha=NUMERIC_ONLY)

# Model input dimensions — must match Params in BowNumberReader
CRNN_H = 48
CRNN_W = 60
ROBOTO_CONDENSED_BOLD_PATH = (
    Path(__file__).resolve().parent.parent / "fonts" / "RobotoCondensed-Bold.ttf"
)

# ─── Pipeline-matched synthetic sample generator ──────────────────────────────

def random_numeric_string() -> str:
    """Draw 1-199 with the digit-length mix observed in real race data."""
    length = random.choices((1, 2, 3), weights=(0.40, 0.50, 0.10))[0]
    if length == 1:
        return str(random.randint(1, 9))
    if length == 2:
        return str(random.randint(10, 99))
    return str(random.randint(100, 199))


def random_bow_label(alpha_prefix_fraction: float = 0.5) -> str:
    """Draw a numeric label, optionally prefixed by one uppercase letter."""
    number = random_numeric_string()
    if random.random() < alpha_prefix_fraction:
        return random.choice(ALPHA_PREFIXES) + number
    return number


def normalize_polarity(img: np.ndarray) -> np.ndarray:
    """Return dark characters on a light card, ignoring crop padding."""
    height, width = img.shape
    y1, y2 = round(height * 0.2), round(height * 0.8)
    x1, x2 = round(width * 0.2), round(width * 0.8)
    card_center = img[y1:y2, x1:x2]
    return img if card_center.mean() > 128 else cv2.bitwise_not(img)


def synthetic_text_layout(text: str, font_size: int) -> dict[str, object]:
    """Load Roboto Condensed Bold and measure one complete bow label."""
    if not ROBOTO_CONDENSED_BOLD_PATH.is_file():
        raise FileNotFoundError(
            f"Missing synthetic training font: {ROBOTO_CONDENSED_BOLD_PATH}"
        )
    font = ImageFont.truetype(str(ROBOTO_CONDENSED_BOLD_PATH), font_size)
    left, top, right, bottom = font.getbbox(text)
    return {
        "font": font,
        "bbox": (left, top, right, bottom),
        "width": right - left,
        "height": bottom - top,
    }


def make_pipeline_sample(text: str, out_h: int = CRNN_H,
                         light_card: bool = False) -> np.ndarray:
    """
    Generate a synthetic bow-label image that matches the exact
    preprocessing applied by BowNumberPipeline at inference time, including
    polarity auto-detection.

    Parameters
    ----------
    text      : 1-3 digits, optionally prefixed by one A-Z character
    out_h     : output height (must match CRNN_H)
    light_card: if True, render dark text on a light background (inverted card)

    Pipeline:
        render text on a variable gray card → noise and illumination gradient
        → CLAHE → mild sharpen → polarity normalize → fixed-size resize
    """
    render_h = 40
    # Bow cards have a fixed physical size. Do not make card width a shortcut
    # for predicting how many characters it contains.
    render_w = 50

    # 1. Render variable-contrast cards, including the gray backgrounds that
    # previously lost their digit strokes during binary thresholding.
    if light_card:
        background = random.randint(125, 245)
        text_value = max(0, background - random.randint(55, 150))
    else:
        background = random.randint(10, 115)
        text_value = min(255, background + random.randint(65, 180))
    img = np.full((render_h, render_w), background, dtype=np.float32)
    horizontal = np.linspace(
        random.uniform(-30, 30), random.uniform(-30, 30), render_w
    )
    vertical = np.linspace(
        random.uniform(-20, 20), random.uniform(-20, 20), render_h
    )
    img += horizontal[np.newaxis, :] + vertical[:, np.newaxis]
    img = np.clip(img, 0, 255).astype(np.uint8)
    # Render the physical card face in Roboto Condensed Bold. Font size and
    # placement still vary, while later augmentation varies stroke weight.
    font_size = random.randint(24, 34)
    layout = synthetic_text_layout(text, font_size)
    while font_size > 10:
        layout = synthetic_text_layout(text, font_size)
        if int(layout["width"]) <= render_w - 6:
            break
        font_size -= 1
    tw = int(layout["width"])
    th = int(layout["height"])
    left = max(
        2,
        min(render_w - tw - 2,
            (render_w - tw) // 2 + random.randint(-4, 4)),
    )
    top = max(
        2,
        min(render_h - th - 2,
            (render_h - th) // 2 + random.randint(-4, 4)),
    )
    bbox_left, bbox_top, _, _ = layout["bbox"]
    pil_image = Image.fromarray(img)
    ImageDraw.Draw(pil_image).text(
        (left - int(bbox_left), top - int(bbox_top)),
        text,
        font=layout["font"],
        fill=text_value,
    )
    img = np.asarray(pil_image)

    # 2. Gaussian noise
    noise = np.random.normal(0, random.uniform(3, 15), img.shape)
    img   = np.clip(img.astype(np.float32) + noise, 0, 255).astype(np.uint8)

    # 3. Apply the same grayscale-preserving production preprocessing.
    return normalize_grayscale_card(img, CRNN_W, out_h)


def augment_real_crop(img: np.ndarray) -> np.ndarray:
    """Simulate small detector-box and video differences on normalized crops."""
    img = np.clip(
        img.astype(np.float32) * random.uniform(0.75, 1.20)
        + random.uniform(-25, 25),
        0,
        255,
    ).astype(np.uint8)
    height, width = img.shape
    angle = random.uniform(-4.0, 4.0)
    scale = random.uniform(0.88, 1.08)
    tx = random.uniform(-3.0, 3.0)
    ty = random.uniform(-2.0, 2.0)
    matrix = cv2.getRotationMatrix2D((width / 2, height / 2), angle, scale)
    matrix[:, 2] += (tx, ty)
    result = cv2.warpAffine(
        img,
        matrix,
        (width, height),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=255,
    )
    if random.random() < 0.35:
        kernel = np.ones((2, 2), np.uint8)
        result = (cv2.erode(result, kernel) if random.random() < 0.5
                  else cv2.dilate(result, kernel))
    if random.random() < 0.35:
        result = cv2.GaussianBlur(result, (3, 3), random.uniform(0.2, 0.8))
    if random.random() < 0.5:
        quality = random.randint(45, 90)
        encoded = cv2.imencode(".jpg", result,
                               [cv2.IMWRITE_JPEG_QUALITY, quality])[1]
        result = cv2.imdecode(encoded, cv2.IMREAD_GRAYSCALE)
    return result


# ─── CTC decode ────────────────────────────────────────────────────────────────

def ctc_greedy_decode(logits: np.ndarray) -> str:
    """logits: (T, C) -- argmax per timestep, collapse repeats, drop blank."""
    best = logits.argmax(axis=1)
    chars = []
    previous = -1
    for cls in best:
        if cls != previous and cls != BLANK_IDX:
            if not 1 <= cls <= len(CHARACTERS):
                raise ValueError(f"CTC class {cls} is outside the OCR vocabulary")
            chars.append(CHARACTERS[cls - 1])
        previous = cls
    return "".join(chars)


# ─── Dataset ─────────────────────────────────────────────────────────────────

class BowCardDataset(Dataset):
    def __init__(self,
                 n_synthetic: int = 5000,
                 real_data_dir: str = "",
                 real_fraction: float = 0.30,
                 real_alpha_fraction: float = 0.10,
                 alpha_prefix_fraction: float = 0.5,
                 out_h: int = CRNN_H):
        self.n_syn  = n_synthetic
        self.out_h  = out_h
        self.real_fraction = real_fraction
        self.real_alpha_fraction = real_alpha_fraction
        self.alpha_prefix_fraction = alpha_prefix_fraction
        self.real_samples: list[tuple[np.ndarray, str]] = []
        self.real_alpha_samples: list[tuple[np.ndarray, str]] = []

        if real_data_dir and os.path.isdir(real_data_dir):
            self._load_real(real_data_dir)

        print(f"Configured {n_synthetic} synthetic samples per epoch.")

    def _load_real(self, data_dir: str) -> None:
        """
        Load real labelled crops.
        Naming convention: <label>_<anything>.png, e.g. E43_frame042.png.
        The label (up to the first underscore) may have one A-Z prefix.
        """
        loaded = 0
        for p in Path(data_dir).rglob("*.png"):
            label = training_label(p.stem.split("_")[0])
            if is_valid_bow_label(label):
                img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
                if img is not None:
                    img = normalize_polarity(img)
                    if img.shape != (self.out_h, CRNN_W):
                        img = cv2.resize(img, (CRNN_W, self.out_h),
                                         interpolation=cv2.INTER_AREA)
                    self.real_samples.append((img, label))
                    if label[0] in ALPHA_PREFIXES:
                        self.real_alpha_samples.append((img, label))
                    loaded += 1
        print(
            f"Loaded {loaded} real crops from {data_dir} "
            f"({len(self.real_alpha_samples)} alpha-prefixed)"
        )

    def __len__(self) -> int:
        return self.n_syn

    def __getitem__(self, idx: int):
        if self.real_samples and random.random() < self.real_fraction:
            samples = (
                self.real_alpha_samples
                if self.real_alpha_samples
                and random.random() < self.real_alpha_fraction
                else self.real_samples
            )
            img, label = random.choice(samples)
            img = augment_real_crop(img)
        else:
            label = random_bow_label(
                0.0 if NUMERIC_ONLY else self.alpha_prefix_fraction
            )
            light_card = random.random() < 0.5
            img = make_pipeline_sample(
                label,
                self.out_h,
                light_card=light_card,
            )

        tensor = torch.from_numpy(img.astype(np.float32) / 255.0).unsqueeze(0)  # (1,H,W)
        target = torch.tensor([CHAR_TO_IDX[c] for c in label], dtype=torch.long)
        return tensor, target


def collate_batch(batch):
    """Pad variable-width images to the batch max width (right-padded with
    white/background) and concatenate CTC targets with their lengths."""
    images, targets = zip(*batch)
    widths = [img.shape[2] for img in images]
    max_w = max(widths)
    padded = []
    for img in images:
        pad_amount = max_w - img.shape[2]
        if pad_amount > 0:
            img = nn.functional.pad(img, (0, pad_amount), value=1.0)
        padded.append(img)
    image_batch = torch.stack(padded, dim=0)  # (B, 1, H, W_max)
    target_lengths = torch.tensor([len(t) for t in targets], dtype=torch.long)
    target_batch = torch.cat(targets) if targets else torch.zeros(0, dtype=torch.long)
    input_lengths = torch.tensor([width // 4 for width in widths], dtype=torch.long)
    return image_batch, target_batch, target_lengths, input_lengths


# ─── Model ───────────────────────────────────────────────────────────────────

class BowCRNN(nn.Module):
    """
    CTC CRNN for whole bow-number recognition.

    Input  : (B, 1, H, W)  — grayscale, normalised [0,1]
    Output : (T, B, C)     — time-major logits  (T = W/4, C = NUM_CLASSES)

    At inference the output is decoded with greedy CTC (argmax per timestep,
    collapse repeats, drop blank).
    """
    def __init__(self, num_classes: int | None = None,
                 h: int = CRNN_H):
        super().__init__()
        num_classes = NUM_CLASSES if num_classes is None else num_classes
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2, 2),                           # H→H/2
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2, 2),                           # H→H/4
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
        )
        self.rnn = nn.GRU(128 * (h // 4), 256, num_layers=2,
                          batch_first=True, bidirectional=True)
        self.fc  = nn.Linear(512, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        f = self.cnn(x)                               # (B, 128, H/4, W/4)
        b, c, hh, w = f.shape
        f = f.permute(0, 3, 1, 2).contiguous().view(b, w, c * hh)
        o, _ = self.rnn(f)                            # (B, W/4, 512)
        return self.fc(o).permute(1, 0, 2)            # (T, B, C) time-major


# ─── Training ─────────────────────────────────────────────────────────────────

def load_real_samples(data_dir: str) -> list[tuple[torch.Tensor, str]]:
    samples = []
    if not data_dir or not os.path.isdir(data_dir):
        return samples
    for path in sorted(Path(data_dir).rglob("*.png")):
        label = training_label(path.stem.split("_")[0])
        if not is_valid_bow_label(label):
            continue
        img = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue
        img = normalize_polarity(img)
        img = cv2.resize(img, (CRNN_W, CRNN_H), interpolation=cv2.INTER_AREA)
        tensor = torch.from_numpy(img.astype(np.float32) / 255.0)[None, None]
        samples.append((tensor, label))
    return samples


def make_alpha_validation_samples() -> list[tuple[torch.Tensor, str]]:
    """Build a deterministic validation set spanning every A-Z prefix."""
    if NUMERIC_ONLY:
        return []
    python_random_state = random.getstate()
    numpy_random_state = np.random.get_state()
    random.seed(0)
    np.random.seed(0)
    samples = []
    try:
        validation_cases = tuple(
            (suffix, light_card)
            for suffix in ("1", "43", "128")
            for light_card in (True, False)
        )
        for prefix in ALPHA_PREFIXES:
            for suffix, light_card in validation_cases:
                label = prefix + suffix
                image = make_pipeline_sample(label, light_card=light_card)
                tensor = torch.from_numpy(
                    image.astype(np.float32) / 255.0
                )[None, None]
                samples.append((tensor, label))
    finally:
        random.setstate(python_random_state)
        np.random.set_state(numpy_random_state)
    return samples


def string_accuracy(model: nn.Module,
                    samples: list[tuple[torch.Tensor, str]],
                    device: torch.device) -> tuple[int, int]:
    model.eval()
    correct = 0
    with torch.no_grad():
        for image, label in samples:
            logits = model(image.to(device)).detach().cpu().numpy()[:, 0, :]
            correct += ctc_greedy_decode(logits) == label
    return correct, len(samples)


def train(args: argparse.Namespace) -> None:
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"Device: {device}")
    print(f"Vocabulary: {args.vocabulary} ({NUM_CLASSES} CTC classes)")

    dataset = BowCardDataset(
        n_synthetic = args.samples,
        real_data_dir = args.real_data or "",
        real_fraction = args.real_fraction,
        real_alpha_fraction = args.real_alpha_fraction,
        alpha_prefix_fraction = args.alpha_prefix_fraction,
    )
    loader = DataLoader(dataset, batch_size=args.batch_size,
                        shuffle=True, num_workers=0, collate_fn=collate_batch)
    validation_samples = load_real_samples(args.validation_data)
    print(f"Loaded {len(validation_samples)} held-out real validation crops")
    real_alpha_validation_samples = [
        sample for sample in validation_samples if sample[1][0] in ALPHA_PREFIXES
    ]
    print(
        f"Found {len(real_alpha_validation_samples)} held-out real "
        "alpha-prefixed crops"
    )
    alpha_validation_samples = make_alpha_validation_samples()
    print(f"Configured {len(alpha_validation_samples)} A-Z validation samples")

    model = BowCRNN(NUM_CLASSES).to(device)
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

    ctc   = nn.CTCLoss(blank=BLANK_IDX, zero_infinity=True)
    opt   = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)

    best_loss = float("inf")
    best_selection_accuracy = -1.0
    best_real_accuracy = -1.0
    best_alpha_accuracy = -1.0
    epochs_without_improvement = 0
    checkpoint_path = Path(args.output).with_suffix(".best.pt")
    for epoch in range(1, args.epochs + 1):
        model.train()
        total = 0.0; correct = 0; count = 0; steps = 0

        for imgs, targets, target_lengths, input_lengths in loader:
            imgs, targets = imgs.to(device), targets.to(device)
            logits  = model(imgs)                       # (T, B, C)
            log_probs = logits.log_softmax(dim=2)
            _, b, _ = logits.shape

            # CTCLoss is not implemented natively by every MPS-enabled PyTorch
            # release. Keep the CRNN on the GPU and calculate only its small
            # sequence loss on the CPU; autograd carries gradients back to MPS.
            if device.type == "mps":
                loss = ctc(log_probs.cpu(), targets.cpu(),
                           input_lengths, target_lengths)
            else:
                loss = ctc(log_probs, targets, input_lengths, target_lengths)
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step()
            total += loss.item(); steps += 1

            with torch.no_grad():
                preds = logits.detach().cpu().numpy()  # (T, B, C)
                offset = 0
                for i in range(b):
                    label = "".join(
                        CHARACTERS[c - 1] for c in
                        targets[offset:offset + target_lengths[i]].tolist()
                    )
                    offset += target_lengths[i].item()
                    sequence_length = input_lengths[i].item()
                    if ctc_greedy_decode(preds[:sequence_length, i, :]) == label:
                        correct += 1
                    count += 1

        sched.step()
        avg = total / max(1, steps)
        acc = 100.0 * correct / max(1, count)
        validation_correct, validation_total = string_accuracy(
            model, validation_samples, device)
        validation_accuracy = (
            validation_correct / validation_total if validation_total else -1.0
        )
        real_alpha_correct, real_alpha_total = string_accuracy(
            model, real_alpha_validation_samples, device
        )

        alpha_correct, alpha_total = string_accuracy(
            model, alpha_validation_samples, device
        )
        alpha_accuracy = (
            alpha_correct / alpha_total if alpha_total else validation_accuracy
        )
        validation_text = (
            f"real_val={validation_correct}/{validation_total} "
            f"({validation_accuracy:.1%})"
            if validation_total else "real_val=unavailable"
        )
        alpha_text = (
            f"real_alpha={real_alpha_correct}/{real_alpha_total}  "
            f"alpha_val={alpha_correct}/{alpha_total} ({alpha_accuracy:.1%})  "
            if alpha_total else ""
        )
        print(f"  Epoch {epoch:3d}/{args.epochs}  "
              f"loss={avg:.4f}  train_acc={acc:.1f}%  {validation_text}  "
              f"{alpha_text}lr={sched.get_last_lr()[0]:.2e}")

        if NUMERIC_ONLY:
            selection_accuracy = (
                validation_accuracy if validation_total else acc / 100.0
            )
        else:
            selection_accuracy = (
                (validation_accuracy + alpha_accuracy) / 2
                if validation_total else alpha_accuracy
            )
        validation_improved = selection_accuracy > best_selection_accuracy
        improved = (
            validation_improved or
            (selection_accuracy == best_selection_accuracy and avg < best_loss)
        )
        if improved:
            best_loss = avg
            best_selection_accuracy = selection_accuracy
            best_real_accuracy = validation_accuracy
            best_alpha_accuracy = alpha_accuracy
            torch.save(model.state_dict(), checkpoint_path)
        if validation_improved:
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
            if args.patience and epochs_without_improvement >= args.patience:
                print(f"Early stopping after {args.patience} epochs without "
                      "validation improvement")
                break

    print(f"\nBest training loss: {best_loss:.4f}")
    if validation_samples:
        print(f"Selected real validation accuracy: {best_real_accuracy:.1%}")
    if not NUMERIC_ONLY:
        print(f"Selected A-Z validation accuracy: {best_alpha_accuracy:.1%}")

    # Export
    model.load_state_dict(
        torch.load(checkpoint_path, map_location=device))
    if not args.keep_checkpoint:
        checkpoint_path.unlink(missing_ok=True)
    _export(model, args.output)
    _verify(
        args.output,
        args.validation_data,
        args.min_real_accuracy,
        args.min_alpha_accuracy,
    )


def _export(model: nn.Module, output_path: str) -> None:
    # ONNX export operates on CPU tensors even when training used CUDA or MPS.
    model = model.to("cpu").eval()
    dummy = torch.zeros(1, 1, CRNN_H, CRNN_W)
    with torch.no_grad():
        torch.onnx.export(
            model, dummy, output_path,
            input_names  = ["input"],
            output_names = ["output"],
            dynamic_axes = {"input":  {3: "width"},
                            "output": {0: "seq_len"}},
            opset_version       = 11,
            dynamo              = False,
            export_params       = True,
            do_constant_folding = True,
        )
    sz = os.path.getsize(output_path) // 1024
    print(f"Exported: {output_path}  ({sz} KB)")


def _verify(model_path: str, validation_data: str = "",
            min_real_accuracy: float = 0.0,
            min_alpha_accuracy: float = 0.8) -> None:
    """Smoke-test against freshly rendered synthetic samples of varying length."""
    import onnxruntime as ort
    sess = ort.InferenceSession(model_path,
                                providers=["CPUExecutionProvider"])

    def infer(text: str) -> str:
        img = make_pipeline_sample(text)
        inp = img.astype(np.float32)[np.newaxis, np.newaxis] / 255.0
        out = sess.run(None, {"input": inp})[0]   # (T, 1, C)
        if out.ndim != 3 or out.shape[2] != NUM_CLASSES:
            raise RuntimeError(
                f"Unexpected OCR output shape {out.shape}; expected "
                f"(T, 1, {NUM_CLASSES})"
            )
        return ctc_greedy_decode(out[:, 0, :])

    python_random_state = random.getstate()
    numpy_random_state = np.random.get_state()
    random.seed(1)
    np.random.seed(1)
    try:
        test_cases = list("123456789") + [
            random_numeric_string() for _ in range(10)
        ]
        if not NUMERIC_ONLY:
            test_cases += [
                f"{prefix}{random_numeric_string()}" for prefix in ALPHA_PREFIXES
            ]
        predictions = [(case, infer(case)) for case in test_cases]
    finally:
        random.setstate(python_random_state)
        np.random.set_state(numpy_random_state)
    correct = sum(1 for case, prediction in predictions if prediction == case)
    pct     = 100 * correct // len(test_cases)
    print(f"\nString accuracy (synthetic hold-out, mixed lengths): "
          f"{correct}/{len(test_cases)} = {pct}%")
    print("Predictions:")
    for case, prediction in predictions:
        print(
            f"  {case}:{'✓' if prediction == case else prediction + '✗'}",
            end="  ",
        )
    print()

    alpha_samples = make_alpha_validation_samples()
    if alpha_samples:
        alpha_correct = 0
        for image, label in alpha_samples:
            logits = sess.run(None, {"input": image.numpy()})[0][:, 0, :]
            alpha_correct += ctc_greedy_decode(logits) == label
        alpha_accuracy = alpha_correct / len(alpha_samples)
        print(f"Fixed A-Z full-string accuracy: {alpha_correct}/"
              f"{len(alpha_samples)} = {alpha_accuracy:.1%}")
        if alpha_accuracy < min_alpha_accuracy:
            raise RuntimeError(
                f"A-Z validation accuracy {alpha_accuracy:.1%} is below required "
                f"{min_alpha_accuracy:.1%}"
            )

    validation_samples = load_real_samples(validation_data)
    if validation_samples:
        correct = 0
        for image, label in validation_samples:
            logits = sess.run(None, {"input": image.numpy()})[0][:, 0, :]
            correct += ctc_greedy_decode(logits) == label
        accuracy = correct / len(validation_samples)
        print(f"Held-out real full-string accuracy: {correct}/"
              f"{len(validation_samples)} = {accuracy:.1%}")
        if accuracy < min_real_accuracy:
            raise RuntimeError(
                f"Real validation accuracy {accuracy:.1%} is below required "
                f"{min_real_accuracy:.1%}")
        real_alpha_samples = [
            sample for sample in validation_samples
            if sample[1][0] in ALPHA_PREFIXES
        ]
        if real_alpha_samples:
            alpha_correct = 0
            for image, label in real_alpha_samples:
                logits = sess.run(None, {"input": image.numpy()})[0][:, 0, :]
                alpha_correct += ctc_greedy_decode(logits) == label
            print(
                "Held-out real alpha-prefix accuracy: "
                f"{alpha_correct}/{len(real_alpha_samples)} = "
                f"{alpha_correct / len(real_alpha_samples):.1%}"
            )


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(
        description="Train CTC CRNN for bow-number OCR and export to ONNX.")
    p.add_argument("--epochs",     type=int,   default=50)
    p.add_argument("--samples",    type=int,   default=5000,
                   help="Synthetic training samples (default 5000)")
    p.add_argument("--batch-size", type=int,   default=128)
    p.add_argument("--lr",         type=float, default=1e-3)
    p.add_argument(
        "--patience",
        type=int,
        default=15,
        help="Epochs without validation improvement before stopping",
    )
    p.add_argument(
        "--real-fraction",
        type=float,
        default=0.30,
        help="Fraction of batches sampled from real crops when available",
    )
    p.add_argument(
        "--real-data",
        type=str,
        default=str(Path(__file__).resolve().parent.parent / "training_crops"),
        help="Directory of real labelled crops "
             "(default: native/bowdetect/training_crops)",
    )
    p.add_argument(
        "--real-alpha-fraction",
        type=float,
        default=0.10,
        help="Fraction of real samples drawn from alpha-prefixed crops",
    )
    p.add_argument(
        "--alpha-prefix-fraction",
        type=float,
        default=0.5,
        help="Fraction of synthetic labels given an A-Z prefix (default 0.5)",
    )
    p.add_argument(
        "--validation-data",
        type=str,
        default="",
        help="Held-out real crops used for checkpoint selection",
    )
    p.add_argument("--output",     type=str,   default="bow_crnn.onnx")
    p.add_argument(
        "--vocabulary",
        choices=("alphanumeric", "numeric"),
        default="alphanumeric",
        help="Output vocabulary: 37-class alphanumeric or 11-class numeric",
    )
    p.add_argument(
        "--keep-checkpoint",
        action="store_true",
        help="Retain the best PyTorch state dictionary next to the ONNX output",
    )
    p.add_argument("--verify",     type=str,   default="",
                   help="Verify an existing ONNX model and exit")
    p.add_argument("--min-real-accuracy", type=float, default=0.0,
                   help="Minimum held-out accuracy required with --verify")
    p.add_argument("--min-alpha-accuracy", type=float, default=0.8,
                   help="Minimum fixed A-Z accuracy required (default 0.8)")
    args = p.parse_args()
    configure_vocabulary(args.vocabulary)

    if not 0.0 <= args.real_fraction <= 1.0:
        p.error("--real-fraction must be between 0 and 1")
    if not 0.0 <= args.alpha_prefix_fraction <= 1.0:
        p.error("--alpha-prefix-fraction must be between 0 and 1")
    if not 0.0 <= args.real_alpha_fraction <= 1.0:
        p.error("--real-alpha-fraction must be between 0 and 1")
    if not 0.0 <= args.min_alpha_accuracy <= 1.0:
        p.error("--min-alpha-accuracy must be between 0 and 1")

    if args.verify:
        _verify(
            args.verify,
            args.validation_data,
            args.min_real_accuracy,
            args.min_alpha_accuracy,
        )
    else:
        train(args)


if __name__ == "__main__":
    main()
