# %% [markdown]
# # Compare YOLOv8s and YOLO26s bow-card detectors
#
# Open this file in Google Colab (or paste its cells into a notebook), select a
# GPU runtime, and run all cells. Upload `card-detector-colab.zip`, generated by
# `make colab-zip`. Both models use the exact same train/validation split.

# %%
import subprocess
import sys

subprocess.check_call(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "-U",
        "ultralytics",
        "onnx",
        "onnxruntime",
        "onnxslim",
        "pandas",
    ]
)

# %%
from pathlib import Path
import json
import shutil
import time
import zipfile

import numpy as np
import onnxruntime as ort
import pandas as pd
import torch
import yaml
from google.colab import files
from ultralytics import YOLO

print("torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
assert torch.cuda.is_available(), "Select Runtime > Change runtime type > GPU"

# %% [markdown]
# Upload the archive made locally with:
#
# ```bash
# cd native/bowdetect
# make colab-zip
# ```

# %%
uploaded = files.upload()
zip_names = [name for name in uploaded if name.lower().endswith(".zip")]
assert len(zip_names) == 1, "Upload exactly one card-detector dataset ZIP"

workspace = Path("/content/bow-card-comparison")
if workspace.exists():
    shutil.rmtree(workspace)
workspace.mkdir(parents=True)
with zipfile.ZipFile(zip_names[0]) as archive:
    archive.extractall(workspace)

dataset = workspace / "card-detector-data"
data_yaml = dataset / "data.yaml"
data = yaml.safe_load(data_yaml.read_text())
data["path"] = str(dataset.resolve())
data_yaml.write_text(yaml.safe_dump(data, sort_keys=False))

for split in ("train", "val"):
    images = list((dataset / split / "images").glob("*"))
    labels = list((dataset / split / "labels").glob("*.txt"))
    print(f"{split}: {len(images)} images, {len(labels)} labels")
    assert len(images) == len(labels) and images

# %% [markdown]
# Change these values if desired. Keep them identical for both runs for a fair
# architecture comparison.

# %%
EPOCHS = 100
PATIENCE = 15
BATCH = 16
IMAGE_SIZE = 640
SEED = 0
MODELS = ("yolov8s.pt", "yolo26s.pt")
project = workspace / "runs"

# %%
rows = []
artifacts = []

for checkpoint in MODELS:
    run_name = Path(checkpoint).stem
    print(f"\n===== Training {checkpoint} =====")
    model = YOLO(checkpoint)
    started = time.perf_counter()
    model.train(
        data=str(data_yaml),
        epochs=EPOCHS,
        patience=PATIENCE,
        batch=BATCH,
        imgsz=IMAGE_SIZE,
        device=0,
        workers=2,
        project=str(project),
        name=run_name,
        seed=SEED,
        deterministic=True,
        exist_ok=True,
    )
    train_seconds = time.perf_counter() - started

    best_pt = project / run_name / "weights" / "best.pt"
    best = YOLO(str(best_pt))
    validation = best.val(
        data=str(data_yaml), imgsz=IMAGE_SIZE, device=0, plots=True
    )
    onnx_path = Path(
        best.export(
            format="onnx",
            imgsz=IMAGE_SIZE,
            opset=17,
            simplify=True,
            dynamic=False,
        )
    )
    artifacts.extend((best_pt, onnx_path))

    session = ort.InferenceSession(
        str(onnx_path), providers=["CPUExecutionProvider"]
    )
    input_info = session.get_inputs()[0]
    output_info = session.get_outputs()[0]
    output = session.run(
        None,
        {input_info.name: np.zeros((1, 3, IMAGE_SIZE, IMAGE_SIZE), np.float32)},
    )[0]
    cpp_compatible = (
        output.ndim == 3 and output.shape[0] == 1 and output.shape[1] == 5
    )

    rows.append(
        {
            "model": checkpoint,
            "epochs_completed": len(pd.read_csv(project / run_name / "results.csv")),
            "train_minutes": train_seconds / 60,
            "precision": float(validation.box.mp),
            "recall": float(validation.box.mr),
            "mAP50": float(validation.box.map50),
            "mAP50-95": float(validation.box.map),
            "onnx_input": str(input_info.shape),
            "onnx_output": str(list(output.shape)),
            "cpp_compatible_1x5xN": cpp_compatible,
            "best_pt": str(best_pt),
            "onnx": str(onnx_path),
        }
    )

comparison = pd.DataFrame(rows).sort_values("mAP50-95", ascending=False)
comparison

# %% [markdown]
# `cpp_compatible_1x5xN` checks the structural contract used by
# `YoloBoxDetector.cpp`. A passing shape is necessary, but visual testing on
# held-out failures is still required before replacing the production model.

# %%
comparison_csv = workspace / "comparison.csv"
comparison_json = workspace / "comparison.json"
comparison.to_csv(comparison_csv, index=False)
comparison_json.write_text(json.dumps(rows, indent=2))

bundle = workspace / "yolo-comparison-results.zip"
with zipfile.ZipFile(bundle, "w", zipfile.ZIP_DEFLATED) as archive:
    archive.write(comparison_csv, comparison_csv.name)
    archive.write(comparison_json, comparison_json.name)
    for artifact in artifacts:
        archive.write(artifact, f"models/{artifact.parent.parent.name}/{artifact.name}")

print(comparison.to_string(index=False))
files.download(str(bundle))
