"""
train_bow_crnn.py
=================
Trains a CRNN model for bow card OCR and exports bow_crnn.onnx.

KEY DESIGN PRINCIPLE — Pipeline-matched synthetic data
-------------------------------------------------------
The synthetic training images are generated by rendering characters and then
applying the IDENTICAL preprocessing pipeline as BowCardDecoder::preprocess():

    render char on dark bg → scale 4× → unsharp mask → threshold → invert

This produces binary white-background / black-text images that look like the
real preprocessed crops fed to the CRNN at inference time, closing the domain
gap between synthetic training data and real camera images.

Inference contract (must match bow_card_decoder.h)
---------------------------------------------------
    Input  "input"  : float32  (1, 1, H=32, W=64)   normalised [0,1]
    Output "output" : float32  (T, 1, NUM_CLS)       time-major logits
    Decode          : mean-pool over T dimension, argmax

Training uses CrossEntropy on the mean-pooled output (equivalent at inference).

Usage
-----
    # Synthetic only (good baseline, ~5 min on CPU)
    python train_bow_crnn.py --epochs 30 --samples 5000 --output bow_crnn.onnx

    # Add real labelled crops for best accuracy
    # Convention: crops/<label>_<anything>.png  e.g.  crops/12_frame042.png
    python train_bow_crnn.py --epochs 50 --real-data crops/ --output bow_crnn.onnx

    # Verify an existing model
    python train_bow_crnn.py --verify bow_crnn.onnx

Requirements
------------
    pip install torch onnx onnxscript opencv-python numpy
"""

import argparse
import os
import random
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# ─── Charset ─────────────────────────────────────────────────────────────────

CHARSET     = "-0123456789"  # index 0 = blank/unknown
NUM_CLASSES = len(CHARSET)
CHAR_TO_IDX = {c: i for i, c in enumerate(CHARSET)}
VALID_CHARS = CHARSET[1:]   # 0-9

# Model input dimensions — must match Params in bow_card_decoder.h
CRNN_W = 64
CRNN_H = 32


# ─── Pipeline-matched synthetic sample generator ──────────────────────────────

def make_pipeline_sample(char: str,
                         out_w: int = CRNN_W,
                         out_h: int = CRNN_H,
                         light_card: bool = False) -> np.ndarray:
    """
    Generate a synthetic character image that matches the exact preprocessing
    applied by BowCardDecoder at inference time, including polarity auto-detection.

    Parameters
    ----------
    char      : character to render
    out_w/h   : output dimensions (must match CRNN_W / CRNN_H)
    light_card: if True, render dark text on a light background (inverted card)

    Pipeline:
        render char → noise → upscale 4× → unsharp mask → binary threshold
        → polarity auto-detect → normalise to black-on-white → resize
    """
    RENDER_H, RENDER_W = 40, 60

    # 1. Render — dark card: white digit on black bg; light card: inverse
    if light_card:
        img        = np.full((RENDER_H, RENDER_W), 220, dtype=np.uint8)
        text_color = (20,)
    else:
        img        = np.zeros((RENDER_H, RENDER_W), dtype=np.uint8)
        text_color = (255,)

    # Randomly choose from sans-serif fonts to improve generalisation
    font      = random.choice([
        cv2.FONT_HERSHEY_DUPLEX,
        cv2.FONT_HERSHEY_SIMPLEX,
    ])
    scale_f   = random.uniform(0.8, 1.4)
    thickness = random.randint(2, 4)
    (tw, th), _ = cv2.getTextSize(char, font, scale_f, thickness)
    cx = max(2, (RENDER_W - tw) // 2 + random.randint(-4, 4))
    cy = min(RENDER_H - 2, (RENDER_H + th) // 2 + random.randint(-4, 4))
    cv2.putText(img, char, (cx, cy), font, scale_f,
                text_color, thickness, cv2.LINE_AA)

    # 2. Gaussian noise
    noise = np.random.normal(0, random.uniform(3, 15), img.shape)
    img   = np.clip(img.astype(np.float32) + noise, 0, 255).astype(np.uint8)

    # 3. Apply BowCardDecoder::preprocess() pipeline (scale=4)
    SCALE   = 4
    up      = cv2.resize(img, None, fx=SCALE, fy=SCALE,
                         interpolation=cv2.INTER_LANCZOS4)
    blurred = cv2.GaussianBlur(up, (0, 0), 1.0)
    sharp   = cv2.addWeighted(up, 2.5, blurred, -1.5, 0)
    sharp   = np.clip(sharp, 0, 255).astype(np.uint8)
    _, thresh = cv2.threshold(sharp, 140, 255, cv2.THRESH_BINARY)

    # 4. Polarity auto-detection (mirrors bow_card_decoder.h)
    #    mean > 128 → mostly white → dark text, keep as-is
    #    mean < 128 → mostly black → white text, invert
    if thresh.mean() > 128:
        normalised = thresh
    else:
        normalised = cv2.bitwise_not(thresh)

    normalised = cv2.copyMakeBorder(normalised, 10, 10, 10, 10,
                                     cv2.BORDER_CONSTANT, value=255)

    # 5. Resize to model input dimensions
    return cv2.resize(normalised, (out_w, out_h))


# ─── Dataset ─────────────────────────────────────────────────────────────────

class BowCardDataset(Dataset):
    def __init__(self,
                 n_synthetic: int = 5000,
                 real_data_dir: str = "",
                 out_w: int = CRNN_W,
                 out_h: int = CRNN_H):
        self.n_syn  = n_synthetic
        self.out_w  = out_w
        self.out_h  = out_h
        self.real_samples: list[tuple[np.ndarray, str]] = []

        if real_data_dir and os.path.isdir(real_data_dir):
            self._load_real(real_data_dir)

        print(f"Configured {n_synthetic} synthetic samples per epoch.")

    def _load_real(self, data_dir: str) -> None:
        """
        Load real labelled crops.
        Naming convention: <label>_<anything>.png  e.g.  12_frame042.png
        For multi-char labels the whole string is the label.
        """
        loaded = 0
        for p in Path(data_dir).glob("*.png"):
            label = p.stem.split("_")[0].upper()
            if all(c in VALID_CHARS for c in label):
                img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
                if img is not None:
                    # Apply the same invert / resize as the inference pipeline
                    img = cv2.resize(img, (self.out_w, self.out_h))
                    self.real_samples.append((img, label))
                    loaded += 1
        print(f"Loaded {loaded} real crops from {data_dir}")

    def __len__(self) -> int:
        return self.n_syn

    def __getitem__(self, idx: int):
        # 30 % real data when available, 70 % freshly generated synthetic data.
        if self.real_samples and random.random() < 0.3:
            img, label = random.choice(self.real_samples)
            char = label[0]
            tensor = torch.from_numpy(
                img.astype(np.float32) / 255.0
            ).unsqueeze(0)
        else:
            char = random.choice(VALID_CHARS)
            # Randomly choose source polarity (50/50 dark/light card).
            light_card = random.random() < 0.5
            tensor = torch.from_numpy(
                make_pipeline_sample(
                    char, self.out_w, self.out_h, light_card=light_card
                ).astype(np.float32) / 255.0
            ).unsqueeze(0)   # (1, H, W)

        return tensor, CHAR_TO_IDX[char]


# ─── Model ───────────────────────────────────────────────────────────────────

class BowCRNN(nn.Module):
    """
    CRNN for single-character bow card recognition.

    Input  : (B, 1, H, W)  — grayscale, normalised [0,1]
    Output : (T, B, C)     — time-major logits  (T = W/4, C = NUM_CLASSES)

    At inference the output is mean-pooled over T and then argmax over C.
    This is equivalent to the CrossEntropy loss used during training.
    """
    def __init__(self, num_classes: int = NUM_CLASSES,
                 h: int = CRNN_H):
        super().__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2, 2),                           # H→H/2
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2, 2),                           # H→H/4
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
        )
        self.rnn = nn.GRU(128 * (h // 4), 256, num_layers=2,
                          batch_first=True, bidirectional=True)
        self.fc  = nn.Linear(512, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        f = self.cnn(x)                               # (B, 128, H/4, W/4)
        b, c, hh, w = f.shape
        f = f.permute(0, 3, 1, 2).contiguous().view(b, w, c * hh)
        o, _ = self.rnn(f)                            # (B, W/4, 512)
        return self.fc(o).permute(1, 0, 2)            # (T, B, C) time-major


# ─── Training ─────────────────────────────────────────────────────────────────

def train(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    dataset = BowCardDataset(
        n_synthetic  = args.samples,
        real_data_dir = args.real_data or "",
    )
    loader = DataLoader(dataset, batch_size=args.batch_size,
                        shuffle=True, num_workers=0)

    model = BowCRNN(NUM_CLASSES).to(device)
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

    ce    = nn.CrossEntropyLoss()
    opt   = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)

    best_loss = float("inf")
    for epoch in range(1, args.epochs + 1):
        model.train()
        total = 0.0; correct = 0; steps = 0

        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)
            logits  = model(imgs)          # (T, B, C)
            pooled  = logits.mean(dim=0)   # (B, C)
            loss    = ce(pooled, labels)
            correct += (pooled.argmax(1) == labels).sum().item()
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step()
            total += loss.item(); steps += 1

        sched.step()
        avg = total / max(1, steps)
        acc = 100.0 * correct / args.samples

        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{args.epochs}  "
                  f"loss={avg:.4f}  train_acc={acc:.1f}%  "
                  f"lr={sched.get_last_lr()[0]:.2e}")

        if avg < best_loss:
            best_loss = avg
            torch.save(model.state_dict(), "/tmp/bow_crnn_best.pt")

    print(f"\nBest loss: {best_loss:.4f}")

    # Export
    model.load_state_dict(
        torch.load("/tmp/bow_crnn_best.pt", map_location=device))
    _export(model, args.output)
    _verify(args.output)


def _export(model: nn.Module, output_path: str) -> None:
    model.eval()
    dummy = torch.zeros(1, 1, CRNN_H, CRNN_W)
    with torch.no_grad():
        torch.onnx.export(
            model, dummy, output_path,
            input_names  = ["input"],
            output_names = ["output"],
            dynamic_axes = {"input":  {3: "width"},
                            "output": {0: "seq_len"}},
            opset_version       = 11,
            dynamo              = False,
            export_params       = True,
            do_constant_folding = True,
        )
    sz = os.path.getsize(output_path) // 1024
    print(f"Exported: {output_path}  ({sz} KB)")


def _verify(model_path: str) -> None:
    """Smoke-test against freshly rendered synthetic samples."""
    import onnxruntime as ort
    sess = ort.InferenceSession(model_path,
                                providers=["CPUExecutionProvider"])

    def infer(char: str) -> str:
        img = make_pipeline_sample(char)
        inp = img.astype(np.float32)[np.newaxis, np.newaxis] / 255.0
        out = sess.run(None, {"input": inp})[0]   # (T, 1, C)
        avg = out[:, 0, :].mean(axis=0)
        best = int(np.argmax(avg))
        return CHARSET[best] if best > 0 else ""

    test_chars = list(VALID_CHARS)
    correct = sum(1 for c in test_chars if infer(c) == c)
    pct     = 100 * correct // len(test_chars)
    print(f"\nSingle-char accuracy (synthetic hold-out): "
          f"{correct}/{len(test_chars)} = {pct}%")
    print("Predictions:")
    for c in test_chars:
        p = infer(c)
        print(f"  {c}:{'✓' if p == c else p+'✗'}", end="")
    print()


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(
        description="Train CRNN for bow card OCR and export to ONNX.")
    p.add_argument("--epochs",     type=int,   default=30)
    p.add_argument("--samples",    type=int,   default=5000,
                   help="Synthetic training samples (default 5000)")
    p.add_argument("--batch-size", type=int,   default=128)
    p.add_argument("--lr",         type=float, default=1e-3)
    p.add_argument(
        "--real-data",
        type=str,
        default=str(Path(__file__).with_name("training_crops")),
        help="Directory of real labelled crops "
             "(default: native/bowdetect/training_crops)",
    )
    p.add_argument("--output",     type=str,   default="bow_crnn.onnx")
    p.add_argument("--verify",     type=str,   default="",
                   help="Verify an existing ONNX model and exit")
    args = p.parse_args()

    if args.verify:
        _verify(args.verify)
    else:
        train(args)


if __name__ == "__main__":
    main()
