"""
train_bow_crnn.py
=================
Trains a CTC CRNN model for whole bow-number OCR (1-3 digits, e.g. "5", "43",
"128") and exports bow_crnn.onnx.

KEY DESIGN PRINCIPLE — Pipeline-matched synthetic data
-------------------------------------------------------
The synthetic training images are generated by rendering digit strings and
then applying the IDENTICAL preprocessing pipeline as BowNumberPipeline's
preprocess step:

    render text on dark bg → scale 4x → unsharp mask → threshold → invert

This produces binary white-background / black-text images that look like the
real preprocessed card crops fed to the CRNN at inference time, closing the
domain gap between synthetic training data and real camera images.

Inference contract (must match BowNumberReader)
-------------------------------------------------
    Input  "input"  : float32  (1, 1, H=32, W)       normalised [0,1], W varies
    Output "output" : float32  (T, 1, NUM_CLS)        time-major logits
    Decode          : greedy CTC — argmax per timestep, collapse consecutive
                       repeats, drop blank (index 0)

This is a genuine sequence model: a single forward pass over the whole card
crop reads however many digits it contains. There's no per-character
cropping, classification, or heuristic stitching involved -- CTC decoding is
what turns per-timestep logits into a string, from ONE pass over ONE image.

Usage
-----
    # Synthetic only (good baseline, ~5 min on CPU)
    python train_bow_crnn.py --epochs 30 --samples 5000 --output bow_crnn.onnx

    # Add real labelled crops for best accuracy
    # Convention: crops/<digits>_<anything>.png  e.g.  crops/43_frame042.png
    python train_bow_crnn.py --epochs 50 --real-data crops/ --output bow_crnn.onnx

    # Verify an existing model
    python train_bow_crnn.py --verify bow_crnn.onnx

Requirements
------------
    pip install torch onnx onnxscript opencv-python numpy
"""

import argparse
import os
import random
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# ─── Charset ─────────────────────────────────────────────────────────────────

CHARSET     = "-0123456789"  # index 0 = CTC blank
BLANK_IDX   = 0
NUM_CLASSES = len(CHARSET)
CHAR_TO_IDX = {c: i for i, c in enumerate(CHARSET)}
VALID_CHARS = CHARSET[1:]   # 0-9

# Model input dimensions — must match Params in BowNumberReader
CRNN_H = 32
OUTPUT_MIN_WIDTH = 24
OUTPUT_MAX_WIDTH = 160

# Real bow numbers are mostly 1-2 digits; 3-digit numbers (e.g. up to ~199)
# occur but are less common.
LENGTH_WEIGHTS = {1: 0.40, 2: 0.45, 3: 0.15}


# ─── Pipeline-matched synthetic sample generator ──────────────────────────────

def random_digit_string() -> str:
    length = random.choices(
        list(LENGTH_WEIGHTS.keys()), weights=list(LENGTH_WEIGHTS.values())
    )[0]
    first = random.choice("123456789") if length > 1 else random.choice(VALID_CHARS)
    rest = "".join(random.choice(VALID_CHARS) for _ in range(length - 1))
    return first + rest


def make_pipeline_sample(text: str, out_h: int = CRNN_H,
                         light_card: bool = False) -> np.ndarray:
    """
    Generate a synthetic digit-string image that matches the exact
    preprocessing applied by BowNumberPipeline at inference time, including
    polarity auto-detection.

    Parameters
    ----------
    text      : digit string to render (1-3 chars)
    out_h     : output height (must match CRNN_H)
    light_card: if True, render dark text on a light background (inverted card)

    Pipeline:
        render text → noise → upscale 4x → unsharp mask → binary threshold
        → polarity auto-detect → normalise to black-on-white → resize
        (height fixed, width scaled to preserve aspect ratio)
    """
    render_h = 40
    render_w = 34 * len(text) + 16

    # 1. Render — dark card: white digits on black bg; light card: inverse
    if light_card:
        img        = np.full((render_h, render_w), 220, dtype=np.uint8)
        text_color = (20,)
    else:
        img        = np.zeros((render_h, render_w), dtype=np.uint8)
        text_color = (255,)

    # Randomly choose from sans-serif fonts to improve generalisation
    font      = random.choice([
        cv2.FONT_HERSHEY_DUPLEX,
        cv2.FONT_HERSHEY_SIMPLEX,
    ])
    scale_f   = random.uniform(0.8, 1.3)
    thickness = random.randint(2, 4)
    (tw, th), _ = cv2.getTextSize(text, font, scale_f, thickness)
    cx = max(2, (render_w - tw) // 2 + random.randint(-4, 4))
    cy = min(render_h - 2, (render_h + th) // 2 + random.randint(-4, 4))
    cv2.putText(img, text, (cx, cy), font, scale_f,
                text_color, thickness, cv2.LINE_AA)

    # 2. Gaussian noise
    noise = np.random.normal(0, random.uniform(3, 15), img.shape)
    img   = np.clip(img.astype(np.float32) + noise, 0, 255).astype(np.uint8)

    # 3. Apply BowNumberPipeline preprocess (scale=4)
    SCALE   = 4
    up      = cv2.resize(img, None, fx=SCALE, fy=SCALE,
                         interpolation=cv2.INTER_LANCZOS4)
    blurred = cv2.GaussianBlur(up, (0, 0), 1.0)
    sharp   = cv2.addWeighted(up, 2.5, blurred, -1.5, 0)
    sharp   = np.clip(sharp, 0, 255).astype(np.uint8)
    _, thresh = cv2.threshold(sharp, 140, 255, cv2.THRESH_BINARY)

    # 4. Polarity auto-detection (mirrors BowNumberPipeline)
    #    mean > 128 → mostly white → dark text, keep as-is
    #    mean < 128 → mostly black → white text, invert
    if thresh.mean() > 128:
        normalised = thresh
    else:
        normalised = cv2.bitwise_not(thresh)

    normalised = cv2.copyMakeBorder(normalised, 10, 10, 10, 10,
                                     cv2.BORDER_CONSTANT, value=255)

    # 5. Resize to fixed height, width scaled to preserve aspect ratio
    crop_h, crop_w = normalised.shape[:2]
    out_w = round(out_h * crop_w / crop_h)
    out_w = max(OUTPUT_MIN_WIDTH, min(OUTPUT_MAX_WIDTH, out_w))
    return cv2.resize(normalised, (out_w, out_h))


# ─── CTC decode ────────────────────────────────────────────────────────────────

def ctc_greedy_decode(logits: np.ndarray) -> str:
    """logits: (T, C) -- argmax per timestep, collapse repeats, drop blank."""
    best = logits.argmax(axis=1)
    chars = []
    previous = -1
    for cls in best:
        if cls != previous and cls != BLANK_IDX:
            chars.append(CHARSET[cls])
        previous = cls
    return "".join(chars)


# ─── Dataset ─────────────────────────────────────────────────────────────────

class BowCardDataset(Dataset):
    def __init__(self,
                 n_synthetic: int = 5000,
                 real_data_dir: str = "",
                 out_h: int = CRNN_H):
        self.n_syn  = n_synthetic
        self.out_h  = out_h
        self.real_samples: list[tuple[np.ndarray, str]] = []

        if real_data_dir and os.path.isdir(real_data_dir):
            self._load_real(real_data_dir)

        print(f"Configured {n_synthetic} synthetic samples per epoch.")

    def _load_real(self, data_dir: str) -> None:
        """
        Load real labelled crops.
        Naming convention: <digits>_<anything>.png  e.g.  43_frame042.png
        The full digit string (up to the first underscore) is the label.
        """
        loaded = 0
        for p in Path(data_dir).glob("*.png"):
            label = p.stem.split("_")[0]
            if label and all(c in VALID_CHARS for c in label) and len(label) <= 3:
                img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
                if img is not None:
                    if img.shape[0] != self.out_h:
                        new_w = round(self.out_h * img.shape[1] / img.shape[0])
                        img = cv2.resize(img, (new_w, self.out_h))
                    self.real_samples.append((img, label))
                    loaded += 1
        print(f"Loaded {loaded} real crops from {data_dir}")

    def __len__(self) -> int:
        return self.n_syn

    def __getitem__(self, idx: int):
        # 30 % real data when available, 70 % freshly generated synthetic data.
        if self.real_samples and random.random() < 0.3:
            img, label = random.choice(self.real_samples)
        else:
            label = random_digit_string()
            light_card = random.random() < 0.5
            img = make_pipeline_sample(label, self.out_h, light_card=light_card)

        tensor = torch.from_numpy(img.astype(np.float32) / 255.0).unsqueeze(0)  # (1,H,W)
        target = torch.tensor([CHAR_TO_IDX[c] for c in label], dtype=torch.long)
        return tensor, target


def collate_batch(batch):
    """Pad variable-width images to the batch max width (right-padded with
    white/background) and concatenate CTC targets with their lengths."""
    images, targets = zip(*batch)
    widths = [img.shape[2] for img in images]
    max_w = max(widths)
    padded = []
    for img in images:
        pad_amount = max_w - img.shape[2]
        if pad_amount > 0:
            img = nn.functional.pad(img, (0, pad_amount), value=1.0)
        padded.append(img)
    image_batch = torch.stack(padded, dim=0)  # (B, 1, H, W_max)
    target_lengths = torch.tensor([len(t) for t in targets], dtype=torch.long)
    target_batch = torch.cat(targets) if targets else torch.zeros(0, dtype=torch.long)
    return image_batch, target_batch, target_lengths


# ─── Model ───────────────────────────────────────────────────────────────────

class BowCRNN(nn.Module):
    """
    CTC CRNN for whole bow-number recognition.

    Input  : (B, 1, H, W)  — grayscale, normalised [0,1]
    Output : (T, B, C)     — time-major logits  (T = W/4, C = NUM_CLASSES)

    At inference the output is decoded with greedy CTC (argmax per timestep,
    collapse repeats, drop blank).
    """
    def __init__(self, num_classes: int = NUM_CLASSES,
                 h: int = CRNN_H):
        super().__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2, 2),                           # H→H/2
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2, 2),                           # H→H/4
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
        )
        self.rnn = nn.GRU(128 * (h // 4), 256, num_layers=2,
                          batch_first=True, bidirectional=True)
        self.fc  = nn.Linear(512, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        f = self.cnn(x)                               # (B, 128, H/4, W/4)
        b, c, hh, w = f.shape
        f = f.permute(0, 3, 1, 2).contiguous().view(b, w, c * hh)
        o, _ = self.rnn(f)                            # (B, W/4, 512)
        return self.fc(o).permute(1, 0, 2)            # (T, B, C) time-major


# ─── Training ─────────────────────────────────────────────────────────────────

def train(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    dataset = BowCardDataset(
        n_synthetic  = args.samples,
        real_data_dir = args.real_data or "",
    )
    loader = DataLoader(dataset, batch_size=args.batch_size,
                        shuffle=True, num_workers=0, collate_fn=collate_batch)

    model = BowCRNN(NUM_CLASSES).to(device)
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

    ctc   = nn.CTCLoss(blank=BLANK_IDX, zero_infinity=True)
    opt   = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)

    best_loss = float("inf")
    for epoch in range(1, args.epochs + 1):
        model.train()
        total = 0.0; correct = 0; count = 0; steps = 0

        for imgs, targets, target_lengths in loader:
            imgs, targets = imgs.to(device), targets.to(device)
            logits  = model(imgs)                       # (T, B, C)
            log_probs = logits.log_softmax(dim=2)
            t, b, _ = logits.shape
            input_lengths = torch.full((b,), t, dtype=torch.long)

            loss = ctc(log_probs, targets, input_lengths, target_lengths)
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step()
            total += loss.item(); steps += 1

            with torch.no_grad():
                preds = logits.detach().cpu().numpy()  # (T, B, C)
                offset = 0
                for i in range(b):
                    label = "".join(
                        CHARSET[c] for c in
                        targets[offset:offset + target_lengths[i]].tolist()
                    )
                    offset += target_lengths[i].item()
                    if ctc_greedy_decode(preds[:, i, :]) == label:
                        correct += 1
                    count += 1

        sched.step()
        avg = total / max(1, steps)
        acc = 100.0 * correct / max(1, count)

        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{args.epochs}  "
                  f"loss={avg:.4f}  train_acc={acc:.1f}%  "
                  f"lr={sched.get_last_lr()[0]:.2e}")

        if avg < best_loss:
            best_loss = avg
            torch.save(model.state_dict(), "/tmp/bow_crnn_best.pt")

    print(f"\nBest loss: {best_loss:.4f}")

    # Export
    model.load_state_dict(
        torch.load("/tmp/bow_crnn_best.pt", map_location=device))
    _export(model, args.output)
    _verify(args.output)


def _export(model: nn.Module, output_path: str) -> None:
    model.eval()
    dummy = torch.zeros(1, 1, CRNN_H, 96)
    with torch.no_grad():
        torch.onnx.export(
            model, dummy, output_path,
            input_names  = ["input"],
            output_names = ["output"],
            dynamic_axes = {"input":  {3: "width"},
                            "output": {0: "seq_len"}},
            opset_version       = 11,
            dynamo              = False,
            export_params       = True,
            do_constant_folding = True,
        )
    sz = os.path.getsize(output_path) // 1024
    print(f"Exported: {output_path}  ({sz} KB)")


def _verify(model_path: str) -> None:
    """Smoke-test against freshly rendered synthetic samples of varying length."""
    import onnxruntime as ort
    sess = ort.InferenceSession(model_path,
                                providers=["CPUExecutionProvider"])

    def infer(text: str) -> str:
        img = make_pipeline_sample(text)
        inp = img.astype(np.float32)[np.newaxis, np.newaxis] / 255.0
        out = sess.run(None, {"input": inp})[0]   # (T, 1, C)
        return ctc_greedy_decode(out[:, 0, :])

    test_cases = (
        list(VALID_CHARS)
        + [random_digit_string() for _ in range(10)]
        + [random_digit_string() for _ in range(10)]
    )
    correct = sum(1 for c in test_cases if infer(c) == c)
    pct     = 100 * correct // len(test_cases)
    print(f"\nString accuracy (synthetic hold-out, mixed lengths): "
          f"{correct}/{len(test_cases)} = {pct}%")
    print("Predictions:")
    for c in test_cases:
        p = infer(c)
        print(f"  {c}:{'✓' if p == c else p + '✗'}", end="  ")
    print()


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(
        description="Train CTC CRNN for bow-number OCR and export to ONNX.")
    p.add_argument("--epochs",     type=int,   default=30)
    p.add_argument("--samples",    type=int,   default=5000,
                   help="Synthetic training samples (default 5000)")
    p.add_argument("--batch-size", type=int,   default=128)
    p.add_argument("--lr",         type=float, default=1e-3)
    p.add_argument(
        "--real-data",
        type=str,
        default=str(Path(__file__).with_name("training_crops")),
        help="Directory of real labelled crops "
             "(default: native/bowdetect/training_crops)",
    )
    p.add_argument("--output",     type=str,   default="bow_crnn.onnx")
    p.add_argument("--verify",     type=str,   default="",
                   help="Verify an existing ONNX model and exit")
    args = p.parse_args()

    if args.verify:
        _verify(args.verify)
    else:
        train(args)


if __name__ == "__main__":
    main()
